name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]
  issue_comment:
    types: [created]

 MY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
      - name: Assign NEW issues and NEW pull requests to project
        uses: srggrs/assign-one-project-github-action@1.3.1
        if: github.event.action == 'opened'
        with:
          project: 'https://github.com/orgs/TheWidlarzGroup/projects/2'
         
