name: Changed Check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run
        run: |
          keyword='modified:   changed.md'
          result=$(git status | grep -i "$keyword")

          if [[ $result == *"$keyword"* ]]; then
            exit 0
          fi
