name: Check Changed

on:
  push:
    branches: [playground/gha]
  pull_request:
    branches: [playground/gha]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check
        run: |
          if [ -s CHANGED.md ]; then
            exit 0
          else
            echo "No changes saved in CHANGED.md"
            exit 1
          fi
