name: 'Deploy Docs'

on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.14
      - name: Install node modules
        run: cd docs/ && yarn
      - name: Deploy
        run: cd docs/ && USE_SSH=true yarn build

      - name: Push to gh-pages branch
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: docs/build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
