name: Publish on Pull Request

on:
  pull_request:
    paths:
      - example-expo/**
      - src/**
jobs:
  pr_build:
    name: Push to Expo Go on Pull Requests
    runs-on: ubuntu-latest
    env:
      EXPO_PROJECT: '@thewidlarzgroup/notificated-example-expo'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn
      - name: PWD
        run: cd example-expo && pwd
      - name: Install YARN
        run: cd example-expo && npm -g install yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: cd example-expo && echo "name=dir::$(yarn cache dir)" >> $GITHUB_STATE
      - uses: expo/expo-github-action@v7
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          expo-cache: true
          expo-version: latest
      - name: Install packages
        run: cd example-expo && yarn install
      - name: EXPO Publish
        run: cd example-expo && expo publish --non-interactive --release-channel ${{ env.RELEASE_CHANNEL }}
        env:
          RELEASE_CHANNEL: ${{github.sha }}
      - name: Add Comment To PR
        uses: mshick/add-pr-comment@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_CHANNEL: ${{github.sha }}
        with:
          message: |
            ## 🚀 📲 Application preview:
            ### Scan with your mobile:
            ![Expo QR](https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=exp://exp.host/${{ env.EXPO_PROJECT }}?release-channel=${{ env.RELEASE_CHANNEL }})
            ### or visit this link:
            Published to https://exp.host/${{ env.EXPO_PROJECT }}?release-channel=${{ env.RELEASE_CHANNEL }}
